### ISSUE TITLE
setup production routes

### ISSUE THREAD

**Issue by Schnitzel** [DigitaleGesellschaft/workadventure#4]

**Comment by Schnitzel** [comment]
@datenreisen 
I woule

**Comment by Schnitzel** [comment]
@datenreisen do you remember the URLs we decided we want to use?

We would need the following URLs:
1. `front` URL (the URL people use to join WA)
2. `pusher` URL (used by WA to talk to the backend, should be `pusher.[front-url]`)

**Comment by datenreisen** [comment]
@Schnitzel we'd like to use:

world.digitale-gesellschaft.ch (xyz.world.digitale-gesellschaft.ch)
world.test.digitale-gesellschaft.ch (xyz.world.test.digitale-gesellschaft.ch

**Comment by datenreisen** [comment]
Change of plan

@Schnitzel we'd like to use:

world.winterkongress.ch (xyz.world.winterkongress.ch)
world.test.winterkongress.ch (xyz.world.test.winterkongress.ch)

**Comment by znerol** [comment]
Done. AFAIK.
